### ISSUE TITLE
目前为止，依旧提示上传目录不存在问题。

### ISSUE THREAD

**Issue by erotic** [panxianhai/kindeditor-for-wordpress#11]
新安装的wordpress 3.8，安装了Kindeditor for wordpress插件，上传图片与批量上传图片功能健全，但是在上传图片100%之后，提示“上传目录不存在”问题。遍寻百度，不得解。求助。

**Comment by panxianhai** [comment]
https://github.com/panxianhai/kindeditor-for-wordpress/commit/165f2a9f8f8b9b2abd9bd786486c3d34b377d7b6  修复了这个问题，目前使用github上面的版本不会有这个问题了，后面上传到wordpress.org上面去。
