### ISSUE TITLE
为何非管理员用户使用就无效

### ISSUE THREAD

**Issue by wblbird** [panxianhai/kindeditor-for-wordpress#12]
非管理员用户往里写东西，点击文章发表或更新，然后编辑器里就什么都没有了

**Comment by panxianhai** [comment]
wordpress 4.1 测试是正常的，可能和浏览器有关系。

**Comment by wavelpc** [comment]
旧版本的插件需要在对应的用户那里，取消 使用可视化编辑器 这个选项就OK了。
