### ISSUE TITLE
上传的图片在发布的时候地址被转码了

### ISSUE THREAD

**Issue by anchep** [panxianhai/kindeditor-for-wordpress#13]
默认添加后的地址是正确的，但是在发布后，地址会自动修改为转码后的地址，具体如何转的，不清楚，但是已经无法正常访问转码后的图片，图片信息为0k。

**Comment by panxianhai** [comment]
@anchep 你是添加网络图片还是本地上传图片，我试了一下好像都不会出现你说的这个情况。

**Comment by anchep** [comment]
已经发现问题，是图片本地化插件造成的。

--- 原始邮件 ---

发件人： "盘先海" <notifications@github.com>
已发： 2015年3月17日 上午8:07
收件人： "panxianhai/kindeditor-for-wordpress" <kindeditor-for-wordpress@noreply.github.com>
抄送： "anchep" <anchep@Hotmail.com>
主题： Re: [kindeditor-for-wordpress] 上传的图片在发布的时候地址被转码了 (#13)

@anchep 你是添加网络图片还是本地上传图片，我试了一下好像都不会出现你说的这个情况。

---
