### ISSUE TITLE
1.4版本为什么要把代码高亮去掉啊？

### ISSUE THREAD

**Issue by oneinstack** [panxianhai/kindeditor-for-wordpress#17]
1.4版本为什么要把代码高亮去掉啊？ 就是因为有高亮功能才用的。。

**Comment by panxianhai** [comment]
那个代码高亮不是太好用，一般用户也不清楚如何设置他们，打算下一个版本集成一个代码高亮插件（Crayon Syntax Highlighter ），会比这个好用很多。

如果急切的使用代码高亮，可以考虑使用1.3.7版本。

**Comment by oneinstack** [comment]
Crayon Syntax Highlighter 语法是否和之前的兼容 ？
还有Crayon Syntax Highlighter 高亮的代码里面如果有关键词链接 会显示源码吗？ 希望像1.3.7里面的高亮不会显示源码。
谢谢！

**Comment by ghost** [comment]
好吧。。。对不起。。。我没看到。。。

**Comment by panxianhai** [comment]
@lj2007331 @Mr1028 我在下一个版本把代码高亮加上吧。

**Comment by ghost** [comment]
Think You   辛苦了。。。。正在忙CDN 

1197970604@qq.com

发件人： 盘先海
发送时间： 2015-03-23 13:22
收件人： panxianhai/kindeditor-for-wordpress
抄送： 漠然
主题： Re: [kindeditor-for-wordpress] 1.4版本为什么要把代码高亮去掉啊？ (#17)
@lj2007331 @Mr1028 我在下一个版本把代码高亮加上吧。

**Comment by foamzou** [comment]
原来是去掉了，我说怎么找也找不到。我还是先用1.3.7吧。加油xianhai~~

**Comment by ghost** [comment]
撸主有捐赠地址吗？？？。。。感谢付出

**Comment by panxianhai** [comment]
@Mr1028 

可以用支付宝进行无压力捐赠。:blush:

![捐赠](http://7xi539.com1.z0.glb.clouddn.com/alipay.png)

**Comment by ghost** [comment]
捐赠了点零钱。。。哈哈 。。有个小问题 问一下，我的 代码高亮 全部都为黑色。。。是编辑器就这样 还是由于主题或BUG 造成的？？

**Comment by foamzou** [comment]
@Mr1028 可以贴出地址看看~另外 @panxianhai 会在新版本中添加一个更棒的代码高亮插件，我们一起期待吧:)

**Comment by ghost** [comment]
sorry  失误失误。。。在插件设置里 我的 默认default，所以没有样式。。。。还有高亮插件。。。。哈哈

**Comment by c0ffee-cat** [comment]
Wordpress 4.1.1升级到最新版的kindeditor-for-wordpress之后，就没有图片上传的功能了，那两个图片上传的按钮都没有了？如何检查？如何修复？

**Comment by panxianhai** [comment]
@woshizoufeng 考虑到之前有人用到了代码高亮功能，新的代码高亮可能兼容起来有问题，所以新版本的代码高亮插件先搁置了。

@kashuorg 1.4.2 有图片上传功能的，确认一下是不是这个版本。

@Mr1028 需要选中才能启用代码高亮，default也是有高亮的，抽空我再确认一下有没有问题。另外，感谢捐赠。
