### ISSUE TITLE
为什么要把上传图片的功能去掉？

### ISSUE THREAD

**Issue by Facebooksx** [panxianhai/kindeditor-for-wordpress#20]
以前用着很顺手，今天突然想上传图片，惊讶的发现没有这个功能了，最新版，不知道作者是怎么想的，硬是逼的我换成别家的工具。

**Comment by panxianhai** [comment]
wordpress自带的上传图片的也很顺手，可以试一下。

这个功能蛮多人需要的，本周争取重新加上，多图上传真的不再添加了。

**Comment by panxianhai** [comment]
@Facebooksx 新版本已经加上了。

**Comment by Facebooksx** [comment]
@panxianhai   我在网上找到旧版本的装上了，期待新版。
