### ISSUE TITLE
wordpress和kindeditor都升级到最新版后，图片上传功能没有了

### ISSUE THREAD

**Issue by c0ffee-cat** [panxianhai/kindeditor-for-wordpress#21]
wordpress和kindeditor都升级到最新版后，图片上传功能没有了

那个两个图片上传的按钮都不见了，无法上传图片

如何解决此问题？谢谢！

**Comment by panxianhai** [comment]
@kashuorg 你的是1.4.2版本的？1.4.2版本是有图片上传功能的。
